# Generated by Django 3.0.8 on 2020-08-30 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField()),
                ('test_date', models.DateTimeField(auto_now=True)),
                ('test_user', models.ManyToManyField(blank=True, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
