# Generated by Django 3.0.8 on 2020-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_test',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
