# Generated by Django 3.0.8 on 2020-08-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_auto_20200830_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer_types',
            new_name='answer_type',
        ),
        migrations.AlterField(
            model_name='answers',
            name='yes_or_no',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
