# Generated by Django 3.0.8 on 2020-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=200)),
                ('au_email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('contact_number', models.IntegerField(unique=True)),
                ('programme', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'rather not say')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
