# Generated by Django 3.0.8 on 2020-09-02 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_number', models.CharField(max_length=20)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('programme', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'male'), ('2', 'female'), ('3', 'rather not say')], max_length=20, null=True)),
                ('last_weekly_update', models.DateTimeField(blank=True, null=True)),
                ('last_daily_update', models.DateTimeField(blank=True, null=True)),
                ('last_screening_date', models.DateTimeField(blank=True, null=True)),
                ('last_screening_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('current_weight', models.IntegerField()),
                ('set_goal', models.CharField(choices=[('<5', '<5'), ('5-10', '5-10'), ('10-15', '10-15'), ('15-25', '15-25')], max_length=200)),
                ('workout_patterns', multiselectfield.db.fields.MultiSelectField(choices=[('Exercise at home', 'Exercise at home'), ('Gyming', 'Gyming'), ('Cycling', 'Cycling'), ('Walk', 'Walk'), ('Yoga', 'Yoga'), ('Zumba', 'Zumba')], max_length=47)),
                ('daily_water', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=200)),
                ('reason', multiselectfield.db.fields.MultiSelectField(choices=[('Peer', 'Peer'), ('Social', 'Social'), ('Self', 'Self'), ('Family', 'Family'), ('Group', 'Group')], max_length=200)),
                ('ongoing_med', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('ongoing_med_reason', models.CharField(max_length=200, null=True)),
                ('menstural_cycle', models.CharField(max_length=200, null=True)),
                ('hours_sleep', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('alcohol', models.IntegerField()),
                ('junkfood', models.CharField(choices=[('Daily', 'Daily'), ('Every alternate day', 'Every alternate day'), ('twice a week', 'twice a week'), ('once a week', 'once a week'), ('once a month', 'once a month')], max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
