# Generated by Django 3.0.8 on 2020-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'male'), ('2', 'female'), ('3', 'rather not say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='programme',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
