# Generated by Django 3.0.8 on 2020-09-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='menstural_cycle',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6+', '6+')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ongoing_med_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
