# Generated by Django 3.1.1 on 2020-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200908_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_updated_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='enrollment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
