# Generated by Django 2.2.8 on 2020-08-05 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200801_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('current_weight', models.IntegerField()),
                ('set_goal', models.CharField(choices=[('<5', '<5'), ('5-10', '5-10'), ('10-15', '10-15'), ('15-25', '15-25')], max_length=200)),
                ('workout_patterns', models.CharField(choices=[('Exercise at home', 'Exercise at home'), ('Gyming', 'Gyming'), ('Cycling', 'Cycling'), ('Walk', 'Walk'), ('Yoga', 'Yoga'), ('Zumba', 'Zumba')], max_length=200)),
                ('daily_water', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=200)),
                ('reason', models.CharField(choices=[('Peer', 'Peer'), ('Social', 'Social'), ('Self', 'Self'), ('Family', 'Family'), ('Group', 'Group')], max_length=200)),
                ('ongoing_med', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('ongoing_med_reason', models.CharField(max_length=200, null=True)),
                ('menstural_cycle', models.CharField(max_length=200, null=True)),
                ('hours_sleep', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('alcohol', models.IntegerField()),
                ('junkfood', models.CharField(choices=[('Daily', 'Daily'), ('Every alternate day', 'Every alternate day'), ('twice a week', 'twice a week'), ('once a week', 'once a week'), ('once a month', 'once a month')], max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
