# Generated by Django 3.0.8 on 2020-08-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200808_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_daily_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_screening_test',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_weekly_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
