# Generated by Django 3.0.8 on 2020-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200830_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_screening_test',
            new_name='last_screening_date',
        ),
        migrations.AddField(
            model_name='account',
            name='last_screening_number',
            field=models.IntegerField(default=0),
        ),
    ]
