# Generated by Django 3.0.8 on 2020-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200830_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_screening_number',
            field=models.IntegerField(default=1),
        ),
    ]
