# Generated by Django 3.0.8 on 2020-09-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200901_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='current_weight',
            new_name='weight',
        ),
    ]
