# Generated by Django 3.1 on 2020-08-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='Post',
        ),
    ]
