# Generated by Django 3.1 on 2020-08-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200816_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='hi', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
